name: Sugar Prices

permissions:
  contents: write

on:
  workflow_dispatch:

  schedule:
    - cron: "0 19 * * 1-5"

jobs:
  run-scraper:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar bibliotecas
        run: |
          pip install requests pandas

      - name: Executar scraper
        run: |
          python sugar_prices.py

      - name: Salvar CSV no GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sugar_prices.csv
          git commit -m "Atualizar preços do açúcar" || echo "Nenhuma alteração"
          git push
